channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=24.0
- pip:
  - mlflow==3.3.2
  - defusedxml==0.7.1
  - matplotlib==3.10.6
  - numpy==2.3.2
  - pandas==2.3.2
  - pyspark==4.0.1
  - scipy==1.16.1
name: mlflow-env
