channels:
- conda-forge
dependencies:
- python=3.10.4
- pip<=25.1
- pip:
  - mlflow==2.14.1
  - defusedxml==0.7.1
  - jaraco-collections==5.1.0
  - jaraco-context==5.3.0
  - jaraco-functools==4.0.1
  - jaraco-text==3.12.1
  - matplotlib==3.8.4
  - more-itertools==10.3.0
  - numpy==1.26.4
  - packaging==24.2
  - pandas<2,==1.5.3
  - pyspark==3.5.1
  - scipy==1.13.1
name: mlflow-env
